## 아이리스 품종 분류

* github csv url:https://raw.githubusercontent.com/backdew/tensorflow1/master/csv/iris.csv

In [7]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [8]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [9]:
# 원핫인코딩
인코딩 = pd.get_dummies(아이리스) #신기방기 행복
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [10]:
# 독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [11]:
# 2. 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation = 'softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',metrics=['accuracy'])

In [20]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="sigmoid")(X)
H = tf.keras.layers.Dense(8, activation="sigmoid")(H)
H = tf.keras.layers.Dense(8, activation="sigmoid")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics=['accuracy'])

In [24]:
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Train on 150 samples
Epoch 1/10
150/150 [==============================] - 0s 73us/sample - loss: 0.0429 - accuracy: 0.9867
Epoch 2/10
150/150 [==============================] - 0s 100us/sample - loss: 0.0471 - accuracy: 0.9867
Epoch 3/10
150/150 [==============================] - 0s 73us/sample - loss: 0.0434 - accuracy: 0.9867
Epoch 4/10
150/150 [==============================] - 0s 86us/sample - loss: 0.0466 - accuracy: 0.9867
Epoch 5/10
150/150 [==============================] - 0s 173us/sample - loss: 0.0444 - accuracy: 0.9867
Epoch 6/10
150/150 [==============================] - 0s 166us/sample - loss: 0.0481 - accuracy: 0.9867
Epoch 7/10
150/150 [==============================] - 0s 66us/sample - loss: 0.0444 - accuracy: 0.9867
Epoch 8/10
150/150 [==============================] - 0s 100us/sample - loss: 0.0427 - accuracy: 0.9867
Epoch 9/10
150/150 [==============================] - 0s 66us/sample - loss: 0.0456 - accuracy: 0.9800
Epoch 10/10
150/150 [===========================

In [25]:
model.summary()

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_9 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_10 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_11 (Dense)             (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.predict(독립[-5:])

array([[9.3517147e-15, 2.7064711e-03, 9.9729353e-01],
       [4.2474176e-14, 7.2456868e-03, 9.9275428e-01],
       [7.7102489e-14, 1.0704624e-02, 9.8929530e-01],
       [6.8299536e-15, 2.2139961e-03, 9.9778593e-01],
       [4.4957663e-13, 3.3661664e-02, 9.6633834e-01]], dtype=float32)

In [27]:
print(종속[-5:])

품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [28]:
# 학습한 가중치
model.get_weights()

[array([[-0.21971567,  0.1974951 , -0.04187313,  0.3150294 , -0.8304435 ,
         -0.20050998, -0.1144633 ,  0.47710788],
        [ 0.90698   ,  0.41172192, -0.6508556 ,  0.36876634,  0.06458566,
         -0.7616662 ,  0.81382763,  0.456454  ],
        [-0.30052254, -0.33298045,  0.36259484, -0.5951254 ,  1.1970859 ,
          0.71319956, -0.3108917 , -0.9214839 ],
        [-1.1853979 , -1.4280503 ,  1.3127724 , -1.0891556 ,  0.48121312,
          1.0724573 , -1.3359412 , -0.89114165]], dtype=float32),
 array([ 0.7225872 ,  0.80827177, -0.87459445,  0.93599296, -0.77157664,
        -0.7385952 ,  0.6785181 ,  0.6714959 ], dtype=float32),
 array([[-1.8183908 ,  1.2731571 , -1.9168793 ,  1.2629019 ,  1.523396  ,
         -1.042054  ,  1.6246748 ,  0.96383506],
        [-0.40050808,  0.68606305, -0.9317594 ,  1.8150822 ,  1.3509114 ,
         -1.4066586 ,  1.5924014 ,  1.9677408 ],
        [ 1.2865357 , -0.9745858 ,  1.5730358 , -1.007878  , -0.89218724,
          0.51243895, -1.3086545 ,